config/routes.rb
Rails.application.routes.draw do
  root 'home#home'
  get  '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get  '/login'  => 'sessions#new'
  post '/login'  => 'sessions#create'
  get  '/log_in' => 'sessions#destroy'
  resources :users, only: [:show, :index, :edit, :upadte, :destroy] 
  resources :messages, only: [:new, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: :User
  belongs_to :receiver, class_name: :User
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sent_messages, inverse_of: :sender, class_name: :Message
  has_many :received_messages, inverse_of: :receiver, class_name: :Message
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionOperable
end

app/controllers/concerns/session_operable.rb
module SessionOperable
  extend ActiveSupport::Concern

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home; end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    # TODO:あとでmessages/indexにredirectするように変更
    return redirect_to user_path(user) if user && user.authenticate(params[:session][:password])
    render 'new'
  end

  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
   @user = User.new(user_params)
    # TODO:あとでmessages/indexにredirectするように変更
   return redirect_to user_path(@user) if @user.save
   render :new
  end
  
  def show; end
  
  def index
    #とりあえず登録してるユーザーの一覧。
    #showとmessage/newへのリンクをつけたい
    #ここにransack入れたい
  end
  
  def edit
  end
  
  def update
    return redirect_to user_path(@user)
    render :new
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end
    
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_comfirmation)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/home.html.slim
h1 home

p = link_to 'sign up', signup_path
p = link_to 'log in' , login_path

app/views/layouts/_header.html.slim
header message_app

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="UTF-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    meta http-equiv="X-UA-Compatible" content="ie=edge"
    title MessageApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'css/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    main
      = yield
      = debug(params) if Rails.env.development? 

app/views/messages/new.html.slim
h1 message#new

app/views/users/_form.html.slim
/ TODO:タイトル(label)はymlファイルで定義する
p = form.label 'ユーザーネーム'
p = form.text_field :name, placeholder: 'user name'

p = form.label 'メールアドレス'
p = form.text_field :email, placeholder: 'sample@email.com'

p = form.label 'パスワード'
p = form.password_field :password

p = form.label 'パスワード(確認)'
p = form.password_field :password_confirmation

p = form.submit 'アカウント登録'

app/views/users/edit.html.slim
= form_for @user, url: edit_user_path(@user) do |f|
  = render 'form', form: f

app/views/users/new.html.slim
h1 ユーザー登録

= form_for @user, url: users_path do |f|
  = render 'form', form: f

p アカウントをお持ちの方は #{link_to 'ログイン', login_path}

app/views/users/show.html.slim
h1 users#show
p = @user.name
= link_to '編集', edit_user_path(@user)